name = "BezierCurve"
uuid = "6b23c4e3-4a61-45b9-818f-c115e6385f2c"
authors = ["Rikoxo <90527932+Rikoxo@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1.5.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.9"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
