name = "BezierCurve"
uuid = "6b23c4e3-4a61-45b9-818f-c115e6385f2c"
authors = ["Rikoxo <90527932+Rikoxo@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
